[package]
name = "image_collection"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1"
tokio-stream = "^0.1"
crossbeam = "^0.8"
serde = {version = "^1", features = ["derive"]}
serde_json = "1"
futures = "^0.3"
rand = "^0.8"
sqlx = {version="^0.6", features=["sqlite", "runtime-tokio-native-tls"]}
env_logger = "^0.10"
log = "^0.4"
anyhow = "^1"
