[package]
name = "simulation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.9"
actix-files = "0.6.0-beta.7"
tokio = {version="^1.3", features = ["full"]}
tokio-stream = "^0.1.7"
crossbeam = "^0.8"
serde = "^1"
serde_json = "^1"
futures = "^0.3"
rand = "^0.8"
sqlx = {version="^0.5", features=["sqlite", "runtime-actix-native-tls"]}
env_logger = "^0.9"
log = "^0.4"
anyhow = "^1"
image_collection =  {path = "../image_collection"}
