[package]
name = "simulation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.9"
rand = "^0.8"
env_logger = "^0.9"
log = "^0.4"
anyhow = "^1"
image_collection =  {path = "../image_collection"}

